version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

  backend:
    container_name: kwoc-backend
    build: .
    depends_on:
      db:
        # Change this to service_healthy if you want to wait for the database to be healthy before connecting
        condition: service_started

    ports:
      - 5000:5000
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    links:
      - "db"
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
